import type { Block } from 'payload';
import { TeaserCard } from '../TeaserCard/config';
import { RichTextComponent } from '../RichTextComponent/config';

export const Grid: Block = {
  slug: 'grid',
  interfaceName: 'Grid',
  fields: [
    {
      name: 'columns',
      label: 'Ilość kolumn',
      type: 'group',
      fields: [
        {
          name: 'sm',
          label: 'Mobilna (sm)',
          type: 'select',
          required: true,
          defaultValue: '1',
          options: [
            { label: '1 Kolumna', value: '1' },
            { label: '2 Kolumny', value: '2' },
            { label: '3 Kolumny', value: '3' },
            { label: '4 Kolumny', value: '4' },
            { label: '5 Kolumny', value: '5' },
            { label: '6 Kolumny', value: '6' },
            { label: '7 Kolumny', value: '7' },
            { label: '8 Kolumny', value: '8' },
            { label: '9 Kolumny', value: '9' },
            { label: '10 Kolumny', value: '10' },
            { label: '11 Kolumny', value: '11' },
            { label: '12 Kolumny', value: '12' },
          ],
        },
        {
          name: 'md',
          label: 'Tablet (md)',
          type: 'select',
          required: true,
          defaultValue: '2',
          options: [
            { label: '1 Kolumna', value: '1' },
            { label: '2 Kolumny', value: '2' },
            { label: '3 Kolumny', value: '3' },
            { label: '4 Kolumny', value: '4' },
            { label: '5 Kolumny', value: '5' },
            { label: '6 Kolumny', value: '6' },
            { label: '7 Kolumny', value: '7' },
            { label: '8 Kolumny', value: '8' },
            { label: '9 Kolumny', value: '9' },
            { label: '10 Kolumny', value: '10' },
            { label: '11 Kolumny', value: '11' },
            { label: '12 Kolumny', value: '12' },
          ],
        },
        {
          name: 'lg',
          label: 'Desktop (lg)',
          type: 'select',
          required: true,
          defaultValue: '3',
          options: [
            { label: '1 Kolumna', value: '1' },
            { label: '2 Kolumny', value: '2' },
            { label: '3 Kolumny', value: '3' },
            { label: '4 Kolumny', value: '4' },
            { label: '5 Kolumny', value: '5' },
            { label: '6 Kolumny', value: '6' },
            { label: '7 Kolumny', value: '7' },
            { label: '8 Kolumny', value: '8' },
            { label: '9 Kolumny', value: '9' },
            { label: '10 Kolumny', value: '10' },
            { label: '11 Kolumny', value: '11' },
            { label: '12 Kolumny', value: '12' },
          ],
        },
        {
          name: 'xl',
          label: 'Duży ekran (xl)',
          type: 'select',
          required: true,
          defaultValue: '4',
          options: [
            { label: '1 Kolumna', value: '1' },
            { label: '2 Kolumny', value: '2' },
            { label: '3 Kolumny', value: '3' },
            { label: '4 Kolumny', value: '4' },
            { label: '5 Kolumny', value: '5' },
            { label: '6 Kolumny', value: '6' },
            { label: '7 Kolumny', value: '7' },
            { label: '8 Kolumny', value: '8' },
            { label: '9 Kolumny', value: '9' },
            { label: '10 Kolumny', value: '10' },
            { label: '11 Kolumny', value: '11' },
            { label: '12 Kolumny', value: '12' },
          ],
        },
      ],
    },
    {
      name: 'content',
      label: 'Bloki treści',
      type: 'blocks',
      blocks: [TeaserCard, RichTextComponent],
    },
  ],
};
